repos:
  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform fmt
        description: Rewrites all Terraform configuration files to a canonical format
        entry: .pre-commit-hooks/terraform-fmt.sh
        language: script
        files: \.tf$
        exclude: \.+.terraform\/.*$
        require_serial: true

      - id: terraform-validate
        name: Terraform validate
        description: Validates all Terraform configuration files
        entry: .pre-commit-hooks/terraform-validate.sh
        language: script
        files: \.tf$
        exclude: \.+.terraform\/.*$
        require_serial: true

      - id: tflint
        name: tflint
        description: Linter for Terraform source code
        entry: .pre-commit-hooks/tflint.sh
        language: script
        files: \.tf$
        exclude: \.+.terraform\/.*$